# Every bank the picker offers: (id, display name, category, website domain, Wikipedia title or None).
# Categories follow RBI's groupings. Regional Rural Banks reflect the 2025 "one state, one RRB" merger.

PUBLIC = "Public sector"
PRIVATE = "Private sector"
SFB = "Small finance"
PAYMENTS = "Payments bank"
FOREIGN = "Foreign"
RRB = "Regional rural"
COOP = "Co-operative"
OTHER = "Other"

BANKS = [
    # Public sector
    ("sbi", "State Bank of India", PUBLIC, "sbi.co.in", "State Bank of India"),
    ("pnb", "Punjab National Bank", PUBLIC, "pnbindia.in", "Punjab National Bank"),
    ("bob", "Bank of Baroda", PUBLIC, "bankofbaroda.in", "Bank of Baroda"),
    ("canara", "Canara Bank", PUBLIC, "canarabank.com", "Canara Bank"),
    ("union", "Union Bank of India", PUBLIC, "unionbankofindia.co.in", "Union Bank of India"),
    ("boi", "Bank of India", PUBLIC, "bankofindia.co.in", "Bank of India"),
    ("indian", "Indian Bank", PUBLIC, "indianbank.in", "Indian Bank"),
    ("central", "Central Bank of India", PUBLIC, "centralbankofindia.co.in", "Central Bank of India"),
    ("iob", "Indian Overseas Bank", PUBLIC, "iob.in", "Indian Overseas Bank"),
    ("uco", "UCO Bank", PUBLIC, "ucobank.com", "UCO Bank"),
    ("bom", "Bank of Maharashtra", PUBLIC, "bankofmaharashtra.in", "Bank of Maharashtra"),
    ("psb", "Punjab & Sind Bank", PUBLIC, "punjabandsindbank.co.in", "Punjab & Sind Bank"),

    # Private sector
    ("hdfc", "HDFC Bank", PRIVATE, "hdfcbank.com", "HDFC Bank"),
    ("icici", "ICICI Bank", PRIVATE, "icicibank.com", "ICICI Bank"),
    ("axis", "Axis Bank", PRIVATE, "axisbank.com", "Axis Bank"),
    ("kotak", "Kotak Mahindra Bank", PRIVATE, "kotak.com", "Kotak Mahindra Bank"),
    ("indusind", "IndusInd Bank", PRIVATE, "indusind.com", "IndusInd Bank"),
    ("yes", "YES Bank", PRIVATE, "yesbank.in", "Yes Bank"),
    ("idfcfirst", "IDFC FIRST Bank", PRIVATE, "idfcfirstbank.com", "IDFC First Bank"),
    ("idbi", "IDBI Bank", PRIVATE, "idbibank.in", "IDBI Bank"),
    ("federal", "Federal Bank", PRIVATE, "federalbank.co.in", "Federal Bank"),
    ("bandhan", "Bandhan Bank", PRIVATE, "bandhanbank.com", "Bandhan Bank"),
    ("rbl", "RBL Bank", PRIVATE, "rblbank.com", "RBL Bank"),
    ("southindian", "South Indian Bank", PRIVATE, "southindianbank.com", "South Indian Bank"),
    ("karnataka", "Karnataka Bank", PRIVATE, "karnatakabank.com", "Karnataka Bank"),
    ("kvb", "Karur Vysya Bank", PRIVATE, "kvb.co.in", "Karur Vysya Bank"),
    ("cub", "City Union Bank", PRIVATE, "cityunionbank.com", "City Union Bank"),
    ("tmb", "Tamilnad Mercantile Bank", PRIVATE, "tmb.in", "Tamilnad Mercantile Bank"),
    ("jkbank", "Jammu & Kashmir Bank", PRIVATE, "jkbank.com", "Jammu & Kashmir Bank"),
    ("dcb", "DCB Bank", PRIVATE, "dcbbank.com", "DCB Bank"),
    ("csb", "CSB Bank", PRIVATE, "csb.co.in", "CSB Bank"),
    ("dhanlaxmi", "Dhanlaxmi Bank", PRIVATE, "dhanbank.com", "Dhanlaxmi Bank"),
    ("nainital", "Nainital Bank", PRIVATE, "nainitalbank.co.in", "Nainital Bank"),

    # Small finance banks
    ("au", "AU Small Finance Bank", SFB, "aubank.in", "AU Small Finance Bank"),
    ("equitas", "Equitas Small Finance Bank", SFB, "equitasbank.com", "Equitas Small Finance Bank"),
    ("ujjivan", "Ujjivan Small Finance Bank", SFB, "ujjivansfb.in", "Ujjivan Small Finance Bank"),
    ("jana", "Jana Small Finance Bank", SFB, "janabank.com", "Jana Small Finance Bank"),
    ("suryoday", "Suryoday Small Finance Bank", SFB, "suryodaybank.com", "Suryoday Small Finance Bank"),
    ("utkarsh", "Utkarsh Small Finance Bank", SFB, "utkarsh.bank", "Utkarsh Small Finance Bank"),
    ("esaf", "ESAF Small Finance Bank", SFB, "esafbank.com", "ESAF Small Finance Bank"),
    ("capital", "Capital Small Finance Bank", SFB, "capitalbank.co.in", "Capital Small Finance Bank"),
    ("shivalik", "Shivalik Small Finance Bank", SFB, "shivalikbank.com", "Shivalik Small Finance Bank"),
    ("unity", "Unity Small Finance Bank", SFB, "theunitybank.com", "Unity Small Finance Bank"),
    ("slice", "slice Small Finance Bank", SFB, "sliceit.com", "North East Small Finance Bank"),

    # Payments banks
    ("ippb", "India Post Payments Bank", PAYMENTS, "ippbonline.com", "India Post Payments Bank"),
    ("airtel", "Airtel Payments Bank", PAYMENTS, "airtel.in", "Airtel Payments Bank"),
    ("fino", "Fino Payments Bank", PAYMENTS, "finobank.com", "Fino Payments Bank"),
    ("jio", "Jio Payments Bank", PAYMENTS, "jiopaymentsbank.com", "Jio Payments Bank"),
    ("paytm", "Paytm Payments Bank", PAYMENTS, "paytmbank.com", "Paytm Payments Bank"),
    ("nsdl", "NSDL Payments Bank", PAYMENTS, "nsdlbank.com", None),
    ("post", "India Post Office Savings", PAYMENTS, "indiapost.gov.in", "India Post"),

    # Foreign banks with Indian branches
    ("sc", "Standard Chartered", FOREIGN, "sc.com", "Standard Chartered"),
    ("hsbc", "HSBC India", FOREIGN, "hsbc.co.in", "HSBC"),
    ("citi", "Citibank", FOREIGN, "citi.com", "Citibank"),
    ("dbs", "DBS Bank India", FOREIGN, "dbs.com", "DBS Bank"),
    ("deutsche", "Deutsche Bank", FOREIGN, "db.com", "Deutsche Bank"),
    ("barclays", "Barclays Bank", FOREIGN, "barclays.in", "Barclays"),
    ("sbm", "SBM Bank India", FOREIGN, "sbmbank.co.in", "SBM Holdings"),
    ("amex", "American Express Banking", FOREIGN, "americanexpress.com", "American Express"),
    ("boa", "Bank of America", FOREIGN, "bankofamerica.com", "Bank of America"),
    ("jpm", "JPMorgan Chase Bank", FOREIGN, "jpmorgan.com", "JPMorgan Chase"),
    ("bnp", "BNP Paribas", FOREIGN, "bnpparibas.com", "BNP Paribas"),
    ("emiratesnbd", "Emirates NBD", FOREIGN, "emiratesnbd.com", "Emirates NBD"),
    ("fab", "First Abu Dhabi Bank", FOREIGN, "bankfab.com", "First Abu Dhabi Bank"),
    ("mashreq", "Mashreq Bank", FOREIGN, "mashreqbank.com", "Mashreq (bank)"),
    ("adcb", "Abu Dhabi Commercial Bank", FOREIGN, "adcb.com", "Abu Dhabi Commercial Bank"),
    ("qnb", "Qatar National Bank", FOREIGN, "qnb.com", "QNB Group"),
    ("doha", "Doha Bank", FOREIGN, "dohabank.com", "Doha Bank"),
    ("mufg", "MUFG Bank", FOREIGN, "mufg.jp", "MUFG Bank"),
    ("mizuho", "Mizuho Bank", FOREIGN, "mizuhogroup.com", "Mizuho Bank"),
    ("smbc", "Sumitomo Mitsui Banking", FOREIGN, "smbc.co.jp", "Sumitomo Mitsui Banking Corporation"),
    ("socgen", "Société Générale", FOREIGN, "societegenerale.com", "Société Générale"),
    ("ca", "Crédit Agricole", FOREIGN, "credit-agricole.com", "Crédit Agricole"),
    ("shinhan", "Shinhan Bank", FOREIGN, "shinhan.com", "Shinhan Bank"),
    ("woori", "Woori Bank", FOREIGN, None, "Woori Bank"),
    ("kookmin", "KB Kookmin Bank", FOREIGN, "kbstar.com", "Kookmin Bank"),
    ("hana", "KEB Hana Bank", FOREIGN, "kebhana.com", "Hana Bank"),
    ("bbk", "Bank of Bahrain and Kuwait", FOREIGN, "bbkonline.com", "Bank of Bahrain and Kuwait"),
    ("rabobank", "Rabobank", FOREIGN, "rabobank.com", "Rabobank"),
    ("icbc", "ICBC", FOREIGN, "icbc.com.cn", "Industrial and Commercial Bank of China"),
    ("ctbc", "CTBC Bank", FOREIGN, "ctbcbank.com", "CTBC Bank"),
    ("boc", "Bank of Ceylon", FOREIGN, "boc.lk", "Bank of Ceylon"),
    ("sonali", "Sonali Bank", FOREIGN, "sonalibank.com.bd", "Sonali Bank"),
    ("natwest", "NatWest Markets", FOREIGN, "natwest.com", "NatWest"),

    # Regional rural banks (after the May 2025 merger, one per state)
    ("rrb_ap", "Andhra Pradesh Grameena Bank", RRB, "apgb.in", None),
    ("rrb_ar", "Arunachal Pradesh Rural Bank", RRB, "apruralbank.co.in", None),
    ("rrb_as", "Assam Gramin Vikash Bank", RRB, "agvbank.co.in", "Assam Gramin Vikash Bank"),
    ("rrb_br", "Bihar Gramin Bank", RRB, "biharbank.in", None),
    ("rrb_cg", "Chhattisgarh Rajya Gramin Bank", RRB, "cgbank.in", "Chhattisgarh Rajya Gramin Bank"),
    ("rrb_gj", "Gujarat Gramin Bank", RRB, "gujaratgraminbank.in", None),
    ("rrb_hr", "Sarva Haryana Gramin Bank", RRB, "shgb.co.in", "Sarva Haryana Gramin Bank"),
    ("rrb_hp", "Himachal Pradesh Gramin Bank", RRB, "hpgb.in", "Himachal Pradesh Gramin Bank"),
    ("rrb_jk", "J&K Grameen Bank", RRB, "jkgb.in", "J&K Grameen Bank"),
    ("rrb_jh", "Jharkhand Rajya Gramin Bank", RRB, "jrgb.in", "Jharkhand Rajya Gramin Bank"),
    ("rrb_ka", "Karnataka Grameena Bank", RRB, "karnatakagraminbank.com", "Karnataka Gramin Bank"),
    ("rrb_kl", "Kerala Gramin Bank", RRB, "keralagbank.com", "Kerala Gramin Bank"),
    ("rrb_mp", "Madhya Pradesh Gramin Bank", RRB, "mpgb.co.in", "Madhya Pradesh Gramin Bank"),
    ("rrb_mh", "Maharashtra Gramin Bank", RRB, "mahagramin.in", "Maharashtra Gramin Bank"),
    ("rrb_mn", "Manipur Rural Bank", RRB, "manipurruralbank.com", None),
    ("rrb_ml", "Meghalaya Rural Bank", RRB, "meghalayaruralbank.co.in", None),
    ("rrb_mz", "Mizoram Rural Bank", RRB, "mizoramruralbank.co.in", None),
    ("rrb_nl", "Nagaland Rural Bank", RRB, "nagalandruralbank.com", None),
    ("rrb_od", "Odisha Grameen Bank", RRB, "odishabank.in", "Odisha Gramya Bank"),
    ("rrb_py", "Puduvai Bharathiar Grama Bank", RRB, "pbgbank.com", None),
    ("rrb_pb", "Punjab Gramin Bank", RRB, "pgb.org.in", "Punjab Gramin Bank"),
    ("rrb_rj", "Rajasthan Gramin Bank", RRB, "rmgb.in", None),
    ("rrb_tn", "Tamil Nadu Grama Bank", RRB, "tamilnadugramabank.com", "Tamil Nadu Grama Bank"),
    ("rrb_ts", "Telangana Grameena Bank", RRB, "tgbhyd.in", "Telangana Grameena Bank"),
    ("rrb_tr", "Tripura Gramin Bank", RRB, "tripuragraminbank.org", "Tripura Gramin Bank"),
    ("rrb_up", "Uttar Pradesh Gramin Bank", RRB, "aryavart-rrb.com", None),
    ("rrb_uk", "Uttarakhand Gramin Bank", RRB, "uttarakhandgraminbank.com", "Uttarakhand Gramin Bank"),
    ("rrb_wb", "West Bengal Gramin Bank", RRB, "pbgbank.in", None),

    # Co-operative banks (large urban and state co-operatives)
    ("saraswat", "Saraswat Co-operative Bank", COOP, "saraswatbank.com", "Saraswat Bank"),
    ("cosmos", "Cosmos Co-operative Bank", COOP, "cosmosbank.com", "Cosmos Co-operative Bank"),
    ("svc", "SVC Co-operative Bank", COOP, "svcbank.com", "SVC Co-operative Bank"),
    ("tjsb", "TJSB Sahakari Bank", COOP, "tjsbbank.co.in", "TJSB Sahakari Bank"),
    ("abhyudaya", "Abhyudaya Co-operative Bank", COOP, "abhyudayabank.co.in", "Abhyudaya Co-operative Bank"),
    ("bharatcoop", "Bharat Co-operative Bank", COOP, "bharatbank.com", None),
    ("nkgsb", "NKGSB Co-operative Bank", COOP, "nkgsb-bank.com", "NKGSB Co-operative Bank"),
    ("janatapune", "Janata Sahakari Bank", COOP, "janatabankpune.com", "Janata Sahakari Bank"),
    ("kalupur", "Kalupur Commercial Co-op Bank", COOP, "kalupurbank.com", "Kalupur Commercial Co-operative Bank"),
    ("apna", "Apna Sahakari Bank", COOP, "apnabank.co.in", None),
    ("zoroastrian", "Zoroastrian Co-operative Bank", COOP, "zoroastrianbank.com", None),
    ("citizencredit", "Citizen Credit Co-operative Bank", COOP, "citizencreditbank.com", None),
    ("mehsana", "Mehsana Urban Co-operative Bank", COOP, "mucbank.com", None),
    ("rnsb", "Rajkot Nagarik Sahakari Bank", COOP, "rnsbindia.com", "Rajkot Nagarik Sahakari Bank"),
    ("nutan", "Nutan Nagarik Sahakari Bank", COOP, "nutanbank.com", None),
    ("amco", "Ahmedabad Mercantile Co-op Bank", COOP, "amcobank.com", None),
    ("dnsb", "Dombivli Nagari Sahakari Bank", COOP, "dnsbank.in", None),
    ("greater", "Greater Bombay Co-operative Bank", COOP, "greaterbank.com", None),
    ("bccb", "Bassein Catholic Co-operative Bank", COOP, "bccb.co.in", None),
    ("parsik", "GP Parsik Sahakari Bank", COOP, "gpparsikbank.com", None),
    ("vasai", "Vasai Vikas Sahakari Bank", COOP, "vasaivikasbank.co.in", None),
    ("janakalyan", "Janakalyan Sahakari Bank", COOP, "janakalyanbank.com", None),
    ("karad", "Karad Urban Co-operative Bank", COOP, None, None),
    ("model", "Model Co-operative Bank", COOP, "modelbank.in", None),
    ("kapol", "Kapol Co-operative Bank", COOP, None, None),
    ("pdcc", "Pune District Central Co-op Bank", COOP, "pdccbank.com", None),
    ("mumbaidcc", "Mumbai District Central Co-op Bank", COOP, "mumbaidistrictbank.com", None),
    ("mscb", "Maharashtra State Co-operative Bank", COOP, "mscbank.com", "Maharashtra State Co-operative Bank"),
    ("keralabank", "Kerala Bank", COOP, "keralabank.co.in", "Kerala Bank"),
    ("tnsc", "Tamil Nadu State Apex Co-op Bank", COOP, "tnscbank.com", None),
    ("apcob", "AP State Co-operative Bank", COOP, "apcob.org", None),
    ("tscab", "Telangana State Co-operative Bank", COOP, "tscab.org", None),
    ("gscb", "Gujarat State Co-operative Bank", COOP, "gscbank.coop", None),
    ("delhistate", "Delhi State Co-operative Bank", COOP, None, None),
    ("hpscb", "HP State Co-operative Bank", COOP, "hpscb.com", None),
    ("kangra", "Kangra Central Co-operative Bank", COOP, "kccb.in", None),
    ("sutex", "Sutex Co-operative Bank", COOP, "sutexbank.in", None),
    ("surat", "Surat People's Co-op Bank", COOP, "spcbl.in", None),
    ("varachha", "Varachha Co-operative Bank", COOP, "varachhabank.com", None),
    ("prime", "Prime Co-operative Bank", COOP, "primebankindia.com", None),
    ("thane", "Thane Bharat Sahakari Bank", COOP, "thanebharatbank.com", None),
    ("jalgaon", "Jalgaon Janata Sahakari Bank", COOP, "jjsbl.com", None),
    ("punepeoples", "Pune People's Co-operative Bank", COOP, "punepeoplesbank.com", None),
]
